Add paste from clipboard support.
HaxeFlixel/flixel-ui pull request #240
Opened 2022-10-30 19:21 UTC by Bogdan2D

While trying to make something, I've noticed that you can't paste text from your clipboard for whatever reason
The more I thought about it, it could really be of help to have such feature added in...

It's not perfect, but it works pretty fine.

2023-08-01 18:38 UTC, DigiEggz commented
I've tested this and it's working well so far. I'd suggest to add functionality for pasting on macOS with the following change:
```
// Copy and paste
if ((FlxG.keys.pressed.CONTROL || FlxG.keys.pressed.WINDOWS) && hasFocus)
{ ...
```
The Windows key registers as the Command key (Cmd-V) on macOS

2023-08-01 19:48 UTC, bog4d commented
> I've tested this and it's working well so far. I'd suggest to add functionality for pasting on macOS with the following change:
> 
> ```
> // Copy and paste
> if ((FlxG.keys.pressed.CONTROL || FlxG.keys.pressed.WINDOWS) && hasFocus)
> { ...
> ```
> 
> The Windows key registers as the Command key (Cmd-V) on macOS.

Good idea! I'll be adding this now. Thank you for the suggestion!! ^^

2023-08-02 18:10 UTC, Geokureli requested changes

2023-08-02 18:10 UTC, Geokureli commented on flixel/addons/ui/FlxInputText.hx
> +		}
Coverage tests are failing because FlxG.keys are only available when `#if FLX_KEYBOARD` is defined. Using FlxG.keys here may not be a good idea, since it does not honor the order in which keys are pressed in the same frame, which can make a significant difference in typing, especially at lower framerates

Take a look at how keyboard events are handled elsewhere in the class: https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxInputText.hx#L332

2023-08-02 18:18 UTC, bog4d commented on flixel/addons/ui/FlxInputText.hx
> +		}
Oh, right. Yeah, I completely disregarded these. I'll be changing this up soon while taking this information into account

2023-08-02 19:17 UTC, Geokureli commented
Ah, clipboard isn't working on html5 because your using `openfl.desktop.Clipboard` the only html5 equiv i can find is: https://api.haxe.org/js/html/Clipboard.html#readText. but this seems to be asyncronous which sounds like a can of worms

2023-08-09 21:46 UTC, DigiEggz commented
I partially have it working in HTML5 using lime.system.Clipboard. We need to register events within FlxInputText—I'll post some code for it soon. The main problem is that I'm encountering a separate strange bug with HaxeFlixel.

Any time I use the keys to paste text, it always works the first time but then subsequent dual key commands no longer work. If I press X or control/command separately I can get text to trace out, but if I press them together they do not register. This problem is only occuring on HTML5 builds.

2023-10-16 15:42 UTC, DigiEggz commented
This PR can be closed now, fixed by #253.

2023-10-16 15:53 UTC, closed without merging