Add paste support for desktop and web + fix maxLength input
HaxeFlixel/flixel-ui pull request #253
Opened 2023-08-10 18:28 UTC by DigiEggz

Add support for desktop paste events and HTML5 javascript paste events by creating a listener that fills the field as the parent text element changes.

2023-08-10 18:43 UTC, Geokureli commented
can't try this right now, but will soon

2023-08-10 18:44 UTC, Geokureli commented
is this still an issue https://github.com/HaxeFlixel/flixel-ui/issues/251?

2023-08-10 18:46 UTC, DigiEggz commented
> is this still an issue #251?

Yes, that issue still persists.

2023-08-10 20:01 UTC, DigiEggz commented
I've adjusted the priority of the KeyboardEvent.KEY_DOWN listener to allow all events. It needs tested to make sure it doesn't interfere with scrolling the page. Fixes #251.

2023-10-05 20:19 UTC, DigiEggz commented
So far, have yet to encounter any issues. Let me know if anything needs adjustment.

2023-10-14 01:34 UTC, Geokureli requested changes
on this branch, paste doesn't work for me on Chrome or Firefox, i set a breakpoint on `case V if (e.ctrlKey):` and it hits but on html5 it's not pasting the clipboard it's only selecting/focusing the text, is this on purpose? is it reading from that textfield at some other place in code?

not sure why I can't paste, I'm able to paste into HaxeUI-Flixel textfields on chrome, I think.

2023-10-15 21:02 UTC, DigiEggz commented
I'll check to see what's going on. It's currently working for me in all mentioned browsers. When trying to paste, are you copying content to paste before or after the application has initialized? I may have some changes incorporated from the latest version of OpenFL.

2023-10-16 15:14 UTC, Geokureli approved these changes

2023-10-16 15:16 UTC, merged

2023-10-16 15:17 UTC, Geokureli commented
Thanks!