fix _slice9 == []
HaxeFlixel/flixel-ui pull request #256
Opened 2023-10-04 19:51 UTC by Nintbros

`[] == []` is `false`, because arrays
i simply changed `_slice9 == []` to `_slice9.length != 4` (in FlxUI9SliceSprite, line 161) which would achieve the intended purpose, i think

2023-10-14 01:11 UTC, Geokureli requested changes

2023-10-14 01:11 UTC, Geokureli commented on flixel/addons/ui/FlxUI9SliceSprite.hx
> +		if (_slice9 == null || _slice9.length != 4)
cool with this change but we should use `FlxG.log.warn` in cases where an invalid array was used, but not when a null array was given since they may specifically want the default 4,4,7,7 array

2023-10-14 08:56 UTC, Nintbros commented on flixel/addons/ui/FlxUI9SliceSprite.hx
> +		if (_slice9 == null || _slice9.length != 4)
So... If the array is null, use the default, and if an invalid one is used, use `FlxG.log.warn` and not change to default?

Sorry, I'm just a bit confused as to what exactly you mean

2023-10-14 15:17 UTC, Geokureli commented on flixel/addons/ui/FlxUI9SliceSprite.hx
> +		if (_slice9 == null || _slice9.length != 4)
change it to the default in both cases, but warn on invalid

2023-10-15 23:18 UTC, Geokureli requested changes

2023-10-15 23:18 UTC, Geokureli commented on flixel/addons/ui/FlxUI9SliceSprite.hx
> +				flixel.FlxG.log.warn("Invalid 9slice array!");
this might throw a null ref, since _slice9 may be null. let's do:
```suggestion
			if (_slice9 != null)
				flixel.FlxG.log.warn("Invalid 9slice array!");
```
that way, if _slice9 isn't null than it must not have a length of 4

2023-10-16 16:54 UTC, Nintbros commented on flixel/addons/ui/FlxUI9SliceSprite.hx
> +				flixel.FlxG.log.warn("Invalid 9slice array!");
Right, didn't think about that one. Whoops

2023-10-16 18:31 UTC, Geokureli approved these changes

2023-10-16 19:11 UTC, merged

2023-10-16 19:11 UTC, Geokureli commented
thanks!